apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    app: {{ include "nginx.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nginx.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - containerPort: 80
          {{- if .Values.httpsEnabled }}
          volumeMounts:
            - name: tls-certs
              mountPath: "/etc/nginx/certs"
              readOnly: true
          {{- end }}
      {{- if .Values.httpsEnabled }}
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ include "nginx.tlsSecretName" . }}
      {{- end }}
